export interface Entry {
  slug: string;
  title: string;
  createdAt: string;
  audioUrl?: string;
  tags?: string[];
  level?: string;
}

// Dynamically import content JSON (this will be generated by the build script)
// In development, if it doesn't exist yet, we return empty array
export async function getAllEntries(): Promise<Entry[]> {
  try {
    // @ts-ignore
    const index = await import('../content/index.json');
    return index.default || index;
  } catch (e) {
    console.warn("Content index not found. Run 'npm run predev' or 'node scripts/generate-index.cjs'");
    return [];
  }
}

// Load markdown content raw string
const markdownFiles = import.meta.glob('../content/entries/*.md', { query: '?raw', import: 'default' });

export async function getEntryContent(slug: string): Promise<string | null> {
  const path = `../content/entries/${slug}.md`;
  const loader = markdownFiles[path];

  if (!loader) {
    return null;
  }

  // @ts-ignore
  const rawContent = await loader();
  return rawContent as string;
}
